set -g mouse on
setw -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Y send-keys -X select-line \; send-keys -X copy-selection-and-cancel

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key C-p send-keys C-p
bind-key C-n send-keys C-n

unbind r
bind r source-file ~/.tmux.conf

set-option -g focus-events on
set-option -sg escape-time 10

set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:sitm=\E[3m:ritm=\E[23m'

set -g history-limit 50000

set -g pane-active-border-style 'fg=#E6745C'
set -g status-style 'fg=gray'
